apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: numzon/user-service:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_DEFAULT_REGION
            - name: HASHI_CORP_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: HASHI_CORP_VAULT_TOKEN
            - name: HASHI_CORP_VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: HASHI_CORP_VAULT_HOST
            - name: HASHI_CORP_VAULT_PORT
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: HASHI_CORP_VAULT_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
    - name: userservice
      protocol: TCP
      port: 80
      targetPort: 80
