apiVersion: v1
kind: Service
metadata:
  name: mssql-srv
spec:
  clusterIP: None
  selector:
    app: mssql
  ports:
    - name: mssql #same name as metadata.name in StatefulSet
      port: 1433
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  serviceName: "mssql-srv" #must match headless service name
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2017-latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              valueFrom:
                secretKeyRef:
                  name: mssql-secrets
                  key: MSSQL_PID
            - name: ACCEPT_EULA
              valueFrom:
                secretKeyRef:
                  name: mssql-secrets
                  key: ACCEPT_EULA
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secrets
                  key: SA_PASSWORD
          volumeMounts:
            - mountPath: "/var/opt/mssql"
              name: mssqldb
  volumeClaimTemplates:
    - metadata:
        name: mssqldb
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: retainstorage
        resources:
          requests:
            storage: 1Gi
